import { Router } from "express";
import { db, casesTable, caseEvidenceTable, groupsTable } from "@workspace/db";
import { eq, and, sql } from "drizzle-orm";
import { requireAuth } from "../lib/auth";
import { logActivity } from "../lib/activity-logger";
import { CreateCaseBody, UpdateCaseBody, AddCaseEvidenceBody } from "@workspace/api-zod";

const router = Router();

const ownsGroup = async (userId: string, groupId: number): Promise<boolean> => {
  const [g] = await db.select().from(groupsTable).where(and(eq(groupsTable.id, groupId), eq(groupsTable.clerkUserId, userId)));
  return !!g;
};

const formatCase = (c: typeof casesTable.$inferSelect) => ({
  ...c,
  createdAt: c.createdAt?.toISOString(),
  updatedAt: c.updatedAt?.toISOString(),
});

router.get("/groups/:groupId/cases", requireAuth, async (req, res) => {
  const userId = (req as any).userId as string;
  const groupId = parseInt(String(req.params.groupId));
  if (!(await ownsGroup(userId, groupId))) { res.status(403).json({ error: "Forbidden" }); return; }
  const status = req.query.status ? String(req.query.status) : "";
  const staffId = req.query.staffId ? parseInt(String(req.query.staffId)) : 0;
  const limit = req.query.limit ? parseInt(String(req.query.limit)) : 0;
  try {
    let cases = await db.select().from(casesTable).where(eq(casesTable.groupId, groupId));
    if (status) cases = cases.filter(c => c.status === status);
    if (staffId) cases = cases.filter(c => c.staffId === staffId);
    if (limit) cases = cases.slice(0, limit);
    res.json(cases.map(formatCase));
  } catch (err) {
    req.log.error({ err }, "listCases error");
    res.status(500).json({ error: "Internal server error" });
  }
});

router.post("/groups/:groupId/cases", requireAuth, async (req, res) => {
  const userId = (req as any).userId as string;
  const groupId = parseInt(String(req.params.groupId));
  if (!(await ownsGroup(userId, groupId))) { res.status(403).json({ error: "Forbidden" }); return; }
  const parsed = CreateCaseBody.safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: parsed.error }); return; }
  try {
    const [c] = await db.insert(casesTable).values({ ...parsed.data, groupId, status: "open", autoGenerated: false, evidenceCount: 0 }).returning();
    await logActivity({
      groupId,
      type: "case_created",
      message: `Created case: ${c.title}`,
      staffUsername: c.staffUsername || undefined,
    });
    res.status(201).json(formatCase(c));
  } catch (err) {
    req.log.error({ err }, "createCase error");
    res.status(500).json({ error: "Internal server error" });
  }
});

router.get("/groups/:groupId/cases/:caseId", requireAuth, async (req, res) => {
  const userId = (req as any).userId as string;
  const groupId = parseInt(String(req.params.groupId));
  const caseId = parseInt(String(req.params.caseId));
  if (!(await ownsGroup(userId, groupId))) { res.status(403).json({ error: "Forbidden" }); return; }
  try {
    const [c] = await db.select().from(casesTable).where(and(eq(casesTable.id, caseId), eq(casesTable.groupId, groupId)));
    if (!c) { res.status(404).json({ error: "Not found" }); return; }
    const evidence = await db.select().from(caseEvidenceTable).where(eq(caseEvidenceTable.caseId, caseId));
    res.json({ ...formatCase(c), evidence: evidence.map(e => ({ ...e, addedAt: e.addedAt.toISOString() })) });
  } catch (err) {
    req.log.error({ err }, "getCase error");
    res.status(500).json({ error: "Internal server error" });
  }
});

router.patch("/groups/:groupId/cases/:caseId", requireAuth, async (req, res) => {
  const userId = (req as any).userId as string;
  const groupId = parseInt(String(req.params.groupId));
  const caseId = parseInt(String(req.params.caseId));
  if (!(await ownsGroup(userId, groupId))) { res.status(403).json({ error: "Forbidden" }); return; }
  const parsed = UpdateCaseBody.safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: parsed.error }); return; }
  try {
    const [c] = await db.update(casesTable).set({ ...parsed.data, updatedAt: new Date() }).where(and(eq(casesTable.id, caseId), eq(casesTable.groupId, groupId))).returning();
    if (!c) { res.status(404).json({ error: "Not found" }); return; }
    const activityType = parsed.data.status === "closed" ? "case_closed" : "case_updated";
    await logActivity({
      groupId,
      type: activityType,
      message: `${activityType === "case_closed" ? "Closed" : "Updated"} case: ${c.title}`,
      staffUsername: c.staffUsername || undefined,
    });
    res.json(formatCase(c));
  } catch (err) {
    req.log.error({ err }, "updateCase error");
    res.status(500).json({ error: "Internal server error" });
  }
});

router.post("/groups/:groupId/cases/:caseId/evidence", requireAuth, async (req, res) => {
  const userId = (req as any).userId as string;
  const groupId = parseInt(String(req.params.groupId));
  const caseId = parseInt(String(req.params.caseId));
  if (!(await ownsGroup(userId, groupId))) { res.status(403).json({ error: "Forbidden" }); return; }
  const parsed = AddCaseEvidenceBody.safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: parsed.error }); return; }
  try {
    const [evidence] = await db.insert(caseEvidenceTable).values({ ...parsed.data, caseId }).returning();
    await db.update(casesTable).set({ evidenceCount: sql`${casesTable.evidenceCount} + 1`, updatedAt: new Date() }).where(eq(casesTable.id, caseId));
    res.status(201).json({ ...evidence, addedAt: evidence.addedAt.toISOString() });
  } catch (err) {
    req.log.error({ err }, "addEvidence error");
    res.status(500).json({ error: "Internal server error" });
  }
});

export default router;
