import { pgTable, serial, text, integer, timestamp, boolean } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { groupsTable } from "./groups";
import { staffTable } from "./staff";

export const casesTable = pgTable("cases", {
  id: serial("id").primaryKey(),
  groupId: integer("group_id").notNull().references(() => groupsTable.id, { onDelete: "cascade" }),
  staffId: integer("staff_id").references(() => staffTable.id, { onDelete: "set null" }),
  staffUsername: text("staff_username"),
  title: text("title").notNull(),
  description: text("description"),
  severity: text("severity").notNull().default("medium"),
  status: text("status").notNull().default("open"),
  autoGenerated: boolean("auto_generated").notNull().default(false),
  aiSummary: text("ai_summary"),
  suggestedAction: text("suggested_action"),
  evidenceCount: integer("evidence_count").notNull().default(0),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const caseEvidenceTable = pgTable("case_evidence", {
  id: serial("id").primaryKey(),
  caseId: integer("case_id").notNull().references(() => casesTable.id, { onDelete: "cascade" }),
  type: text("type").notNull().default("text"),
  content: text("content").notNull(),
  imageUrl: text("image_url"),
  addedAt: timestamp("added_at").defaultNow().notNull(),
});

export const insertCaseSchema = createInsertSchema(casesTable).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertCase = z.infer<typeof insertCaseSchema>;
export type Case = typeof casesTable.$inferSelect;

export const insertEvidenceSchema = createInsertSchema(caseEvidenceTable).omit({ id: true, addedAt: true });
export type InsertEvidence = z.infer<typeof insertEvidenceSchema>;
export type Evidence = typeof caseEvidenceTable.$inferSelect;
